### ISSUE TITLE
SDL is included in a weird manner that messes up my efforts

### ISSUE THREAD

**Issue by soryy708** [jeremyong/SDLpp#1]
I'm working on making a Visual Studio 2013 Express solution & project for SDLpp, but I'm having issues because of the way you include <SDL/SDL.h> in [Font.h](https://github.com/jeremyong/SDLpp/blob/master/include/Font.h), [Renderer.h](https://github.com/jeremyong/SDLpp/blob/master/include/Renderer.h), [SDLpp.h](https://github.com/jeremyong/SDLpp/blob/master/include/SDLpp.h), [Surface.h](https://github.com/jeremyong/SDLpp/blob/master/include/Surface.h), [Text.h](https://github.com/jeremyong/SDLpp/blob/master/include/Text.h), [Texture.h](https://github.com/jeremyong/SDLpp/blob/master/include/Texture.h), [Window.h](https://github.com/jeremyong/SDLpp/blob/master/include/Window.h) and [Color.h](https://github.com/jeremyong/SDLpp/blob/master/include/Color.h).

I've read somewhere that the correct way to include SDL would be like: `#include "SDL.h`
But you do an `#include <SDL/SDL.h>`
Why the `SDL/` prefix? It's not there when you [grab the includes from libsdl.org](http://libsdl.org/download-2.0.php).

While it's a trivial fix, I'd like to get your input and see your point of view. Why do you use `<SDL/SDL.h>` as opposed to `"SDL.h"`? I guess I could make a hack to have Visual Studio accept `<SDL/SDL.h>` syntax but is there any reason to?

**Comment by jeremyong** [comment]
Hi and thanks for your questions.

SDL requires a number of headers (dozens of them) so many people prefer to stick them in an `SDL` folder in a systemwide include folder. Hence `#include <SDL/SDL.h>`. The brackets indicate looking on a systemwide level whereas quotes would indicate prioritizing a library found locally. I develop on Linux so I am using Linux conventions. Feel free to abstract out the includes to a separate header file, and create an option macro to change it.

**Comment by soryy708** [comment]
Thank you for your swift response.

Unlike you, I develop on Windows.
I have my 'include' and my 'lib' folder in an 'SDL' folder. However, my compiler can't find 'SDL/SDL.h' because there's no 'SDL' directory inside 'SDL/include'.
Do you mind if I change all of the `#include <SDL/SDL.h>` to `#include "SDL.h"`? It works on Windows, and it should work on GNU+Linux as well.

**Comment by jeremyong** [comment]
Here's what I suggest.

Make a separate header locally called "SDL_header.h" or something. Then, do something like

``` c++
#ifdef __WIN32__
#include "SDL.h"
#else
#include <SDL/SDL.h>
#endif
```

or something along those lines.

**Comment by soryy708** [comment]
There are multiple problems with your approach:
1. `__WIN32__` may not be defined on all windows systems. Yep, paranoid. Yep, I don't care. Still, worth mentioning.
2. Technically, the correct way to include SDL on Windows would be to `#include <SDL.h>`
3. I'm trying to make a VS2013E solution&project which is going to be in my repository (you can pull it once that's done if you'd like) to make it easier for Windows-ers to build your project. Adding a local header is not really an option in this case.
4. Why go the hacky way if one could just replace everything with `#include "SDL.h"` and have it work on all platforms?

**Comment by jeremyong** [comment]
This has nothing to do with platforms and everything to do with directory structure. You could be on windows with your header files in C:\foo\bar\SDL or something. My suggestion is less about preprocessor macros and more about making it easier for somebody to change the location of the SDL.h header for the entire project in a single place, which would be a great improvement.

**Comment by soryy708** [comment]
It doesn't matter where your SDL directory is. However, things begin to get messy once you mess with the internal structure of that directory.
Mine shipped without an 'SDL2' directory inside the 'include' directory, and I see no reason to add one.
By the way, does it mean anything to you that [SDL_ttf.c has an `#include "SDL.h` at line 34](http://hg.libsdl.org/SDL_ttf/file/1854597a90fd/SDL_ttf.c#l34) as opposed to `#include <SDL.h>` or `#include<SDL/SDL.h>`?

**Comment by jeremyong** [comment]
No it doesn't. The convention is that SDL libraries get installed into the SDL folder. OSX for example, makes an SDL2 folder and when you install SDL2_image, the SDL_image file gets placed in that SDL2 folder. This project is not an extension to SDL and I wouldn't expect people to install these headers along with a system wide SDL install. Please accept that not everybody's setup will be identical and try to be more accommodating. The open source way dictates that if your needs are different, you make changes that make the underlying system more flexible. Not that you need to make others conform to your configuration.

**Comment by soryy708** [comment]
I understand, which is why I opened this issue.
Thing is, I was sure that _you_ were the one who doesn't conform.
I'm now looking into how to make Visual Studio accept `#include <SDL/SDL.h>` without throwing a fit.

**Comment by jeremyong** [comment]
[It's not just me](https://github.com/search?q=SDL%2FSDL.h&type=Code&ref=searchresults) :)

I have no idea how your VS solution is set up but including header files in a nested directory should not be hard for any modern IDE. My previous suggestion still stands.

**Comment by soryy708** [comment]
[Not just me either](https://github.com/search?q=%23include+%22SDL.h%22&type=Code&ref=searchresults).
I also mentioned that [SDL_ttf uses my convention](http://hg.libsdl.org/SDL_ttf/file/1854597a90fd/SDL_ttf.c#l34).

By the way, using `#include "SDL.h"` will work even if you'd have modified your directory the way you like it. In a way, this would "make the system more flexible".

**Comment by soryy708** [comment]
Hey, check [this](http://forums.libsdl.org/viewtopic.php?t=5997) out.
